name: C/C++ CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libncurses5-dev libncursesw5-dev

    - name: Build and Lint check
      run: make

    - name: Run Unit Tests
      run: make test

    - name: Clean up build artifacts
      run: make clean
